CREATE DATABASE DuAn1_QLQN
GO
USE DuAn1_QLQN
GO

--NhanVien
CREATE TABLE NhanVien
(
	Id UNIQUEIDENTIFIER primary key DEFAULT NEWID(),
	TenTK VARCHAR(50) UNIQUE,
	MatKhau VARCHAR(20),
	HoTen NVARCHAR(50),
	NgaySinh DATETIME,
	GioiTinh BIT,
	DiaChi NVARCHAR(50),
	Sdt VARCHAR(10),
	Luong FLOAT,
	Hinh VARCHAR(255),
	TrangThai INT
)

SELECT TenTK,MatKhau,HoTen,NgaySinh,GioiTinh,DiaChi,Sdt,Luong,Hinh,TrangThai FROM NhanVien
SELECT MatKhau,HoTen,NgaySinh,GioiTinh,DiaChi,Sdt,Luong,Hinh,TrangThai FROM NhanVien WHERE TenTK =
SELECT MatKhau,HoTen,NgaySinh,GioiTinh,DiaChi,Sdt,Luong,Hinh,TrangThai FROM NhanVien WHERE TenTK =;
INSERT INTO NhanVien(TenTK,MatKhau,HoTen,NgaySinh,GioiTinh,DiaChi,Sdt,Luong,Hinh,TrangThai)VALUES('anph','lequyan','Lê Qúy An','2003-10-22',0,'Nghệ An','0966861471',2000,'anh1',0)
--KhachHang
CREATE TABLE KhachHang
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),

	MaKH VARCHAR(20) UNIQUE,
	HoTen NVARCHAR(50),
	NgaySinh DATETIME,
	GioiTinh BIT,
	DiaChi NVARCHAR(50),
	Sdt VARCHAR(10)
)

--May
CREATE TABLE May
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Idkh UNIQUEIDENTIFIER,
	IdLM UNIQUEIDENTIFIER,
	MaMay VARCHAR(20) UNIQUE,
	TrangThai INT
)

--LoaiMay
CREATE TABLE LoaiMay
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	TenLoaiMay  NVARCHAR(25),
	DonGiaMay FLOAT
)

--GiamGia
CREATE TABLE GiamGia
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(20),
	Ten NVARCHAR(50),
	NgayBatDau DATETIME,
	NgayKetThuc DATETIME,
	MucGiamGia INT,
	TrangThai INT
)

--HoaDonMay
CREATE TABLE HoaDonMay
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdMay UNIQUEIDENTIFIER,
	IdGG UNIQUEIDENTIFIER,
	MaHD VARCHAR(20),
	TG_BatDau DATETIME,
	TG_KetThuc DATETIME,
	NgayTao DATETIME,
	TrangThai INT
)

--DichVu
CREATE TABLE DichVu
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaDV VARCHAR(20),
	TenDV NVARCHAR(50),
	SoLuong INT,
	GiaBan FLOAT,
	DonVi NVARCHAR(50),
	Hinh VARCHAR(255),
	DanhMuc NVARCHAR(50),
)

--HangNhap
CREATE TABLE HangNhap
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdDV UNIQUEIDENTIFIER,
	Ma VARCHAR(20),
	Ten NVARCHAR(50),
	GiaNhap FLOAT,
	SoLuong INT,
	NgayNhap DATETIME,
	GhiChu NVARCHAR(100)
)
--HoaDonChiTiet
CREATE TABLE HoaDonCT(
IdHD UNIQUEIDENTIFIER,
IdDV UNIQUEIDENTIFIER,
IdGiamGia UNIQUEIDENTIFIER,
SoLuong INT,
DonGia FLOAT,
CONSTRAINT PK_HoaDonCT PRIMARY KEY (IdHD,IdDV,IdGiamGia),
CONSTRAINT FK1 FOREIGN KEY(IdHD) REFERENCES HoaDonMay(Id),
CONSTRAINT FK2 FOREIGN KEY(IdDV) REFERENCES DichVu(Id),
CONSTRAINT FK3 FOREIGN KEY(IdGiamGia) REFERENCES GiamGia(Id),
)
GO

-----TẠO QUAN HỆ GIỮA CÁC BẢNG
--LoaiMay - May
ALTER TABLE May ADD FOREIGN KEY (IdLM) REFERENCES LoaiMay(Id)
--May - KhachHang
ALTER TABLE may ADD FOREIGN KEY (idkh) REFERENCES khachhang(Id)
--HoaDonMay - May
ALTER TABLE HoaDonMay ADD FOREIGN KEY (IdMay) REFERENCES May(Id)
--GiamGia - HoaDonMay
--ALTER TABLE HoaDonMay ADD FOREIGN KEY (IdGG) REFERENCES GiamGia(Id)
--HangNhap - DichVu
ALTER TABLE HangNhap ADD FOREIGN KEY (IdDV) REFERENCES DichVu(Id)


