package View;

/**
 *
 * @author hung duong
 */
public class Frame_GioChoi extends javax.swing.JFrame {

    public Frame_GioChoi() {
        initComponents();
        setTitle("Gio Choi");
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMT1 = new javax.swing.JPopupMenu();
        mneBMT1 = new javax.swing.JMenuItem();
        mneDVT1 = new javax.swing.JMenuItem();
        popMT2 = new javax.swing.JPopupMenu();
        mneBMT2 = new javax.swing.JMenuItem();
        mneDVT2 = new javax.swing.JMenuItem();
        popMT3 = new javax.swing.JPopupMenu();
        mneBMT3 = new javax.swing.JMenuItem();
        mneDVT3 = new javax.swing.JMenuItem();
        popMT4 = new javax.swing.JPopupMenu();
        mneBMT4 = new javax.swing.JMenuItem();
        mneDVT4 = new javax.swing.JMenuItem();
        popMT5 = new javax.swing.JPopupMenu();
        mneBMT5 = new javax.swing.JMenuItem();
        mneDVT5 = new javax.swing.JMenuItem();
        popMT6 = new javax.swing.JPopupMenu();
        mneBMT6 = new javax.swing.JMenuItem();
        mneDVT6 = new javax.swing.JMenuItem();
        popMT7 = new javax.swing.JPopupMenu();
        mneBMT7 = new javax.swing.JMenuItem();
        mneDVT7 = new javax.swing.JMenuItem();
        popMT8 = new javax.swing.JPopupMenu();
        mneBMT8 = new javax.swing.JMenuItem();
        mneDVT8 = new javax.swing.JMenuItem();
        popMT9 = new javax.swing.JPopupMenu();
        mneBMT9 = new javax.swing.JMenuItem();
        mneDVT9 = new javax.swing.JMenuItem();
        popMT10 = new javax.swing.JPopupMenu();
        mneBMT10 = new javax.swing.JMenuItem();
        mneDVT10 = new javax.swing.JMenuItem();
        popMV11 = new javax.swing.JPopupMenu();
        mneBMV11 = new javax.swing.JMenuItem();
        mneDVT11 = new javax.swing.JMenuItem();
        popMV12 = new javax.swing.JPopupMenu();
        mneBMV12 = new javax.swing.JMenuItem();
        mneDVT12 = new javax.swing.JMenuItem();
        popMV13 = new javax.swing.JPopupMenu();
        mneBMV13 = new javax.swing.JMenuItem();
        mneDVT13 = new javax.swing.JMenuItem();
        popMV14 = new javax.swing.JPopupMenu();
        mneBMV14 = new javax.swing.JMenuItem();
        mneDVT14 = new javax.swing.JMenuItem();
        popMV15 = new javax.swing.JPopupMenu();
        mneBMV15 = new javax.swing.JMenuItem();
        mneDVT15 = new javax.swing.JMenuItem();
        popMV16 = new javax.swing.JPopupMenu();
        mneBMV16 = new javax.swing.JMenuItem();
        mneDVT16 = new javax.swing.JMenuItem();
        popMV17 = new javax.swing.JPopupMenu();
        mneBMV17 = new javax.swing.JMenuItem();
        mneDVT17 = new javax.swing.JMenuItem();
        popMV18 = new javax.swing.JPopupMenu();
        mneBMV18 = new javax.swing.JMenuItem();
        mneDVT18 = new javax.swing.JMenuItem();
        popMV19 = new javax.swing.JPopupMenu();
        mneBMV19 = new javax.swing.JMenuItem();
        mneDVT19 = new javax.swing.JMenuItem();
        popMV20 = new javax.swing.JPopupMenu();
        mneBMV20 = new javax.swing.JMenuItem();
        mneDVT20 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        May1 = new javax.swing.JPanel();
        lblMay1 = new javax.swing.JLabel();
        lblNgay1 = new javax.swing.JLabel();
        lblGBD1 = new javax.swing.JLabel();
        lblKhachHang1 = new javax.swing.JLabel();
        lblTrangThai1 = new javax.swing.JLabel();
        May3 = new javax.swing.JPanel();
        lblMay3 = new javax.swing.JLabel();
        May5 = new javax.swing.JPanel();
        lblMay5 = new javax.swing.JLabel();
        May2 = new javax.swing.JPanel();
        lblMay2 = new javax.swing.JLabel();
        May6 = new javax.swing.JPanel();
        lblMay6 = new javax.swing.JLabel();
        May4 = new javax.swing.JPanel();
        lblMay4 = new javax.swing.JLabel();
        May7 = new javax.swing.JPanel();
        lblMay7 = new javax.swing.JLabel();
        May8 = new javax.swing.JPanel();
        lblMay8 = new javax.swing.JLabel();
        May9 = new javax.swing.JPanel();
        lblMay9 = new javax.swing.JLabel();
        May10 = new javax.swing.JPanel();
        lblMay10 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        May11 = new javax.swing.JPanel();
        lblMay11 = new javax.swing.JLabel();
        May13 = new javax.swing.JPanel();
        lblMay13 = new javax.swing.JLabel();
        May15 = new javax.swing.JPanel();
        lblMay15 = new javax.swing.JLabel();
        May12 = new javax.swing.JPanel();
        lblMay12 = new javax.swing.JLabel();
        May16 = new javax.swing.JPanel();
        lblMay16 = new javax.swing.JLabel();
        May14 = new javax.swing.JPanel();
        lblMay14 = new javax.swing.JLabel();
        May17 = new javax.swing.JPanel();
        lblMay17 = new javax.swing.JLabel();
        May18 = new javax.swing.JPanel();
        lblMay18 = new javax.swing.JLabel();
        May19 = new javax.swing.JPanel();
        lblMay19 = new javax.swing.JLabel();
        May20 = new javax.swing.JPanel();
        lblMay20 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();

        mneBMT1.setText("Bật Máy");
        mneBMT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneBMT1ActionPerformed(evt);
            }
        });
        popMT1.add(mneBMT1);

        mneDVT1.setText("Sử Dụng Dịch Vụ");
        mneDVT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneDVT1ActionPerformed(evt);
            }
        });
        popMT1.add(mneDVT1);

        mneBMT2.setText("Bật Máy");
        mneBMT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneBMT2ActionPerformed(evt);
            }
        });
        popMT2.add(mneBMT2);

        mneDVT2.setText("Sử Dụng Dịch Vụ");
        popMT2.add(mneDVT2);

        mneBMT3.setText("Bật Máy");
        mneBMT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneBMT3ActionPerformed(evt);
            }
        });
        popMT3.add(mneBMT3);

        mneDVT3.setText("Sử Dụng Dịch Vụ");
        popMT3.add(mneDVT3);

        mneBMT4.setText("Bật Máy");
        popMT4.add(mneBMT4);

        mneDVT4.setText("Sử Dụng Dịch Vụ");
        popMT4.add(mneDVT4);

        mneBMT5.setText("Bật Máy");
        popMT5.add(mneBMT5);

        mneDVT5.setText("Sử Dụng Dịch Vụ");
        popMT5.add(mneDVT5);

        mneBMT6.setText("Bật Máy");
        popMT6.add(mneBMT6);

        mneDVT6.setText("Sử Dụng Dịch Vụ");
        popMT6.add(mneDVT6);

        mneBMT7.setText("Bật Máy");
        popMT7.add(mneBMT7);

        mneDVT7.setText("Sử Dụng Dịch Vụ");
        popMT7.add(mneDVT7);

        mneBMT8.setText("Bật Máy");
        popMT8.add(mneBMT8);

        mneDVT8.setText("Sử Dụng Dịch Vụ");
        popMT8.add(mneDVT8);

        mneBMT9.setText("Bật Máy");
        popMT9.add(mneBMT9);

        mneDVT9.setText("Sử Dụng Dịch Vụ");
        popMT9.add(mneDVT9);

        mneBMT10.setText("Bật Máy");
        popMT10.add(mneBMT10);

        mneDVT10.setText("Sử Dụng Dịch Vụ");
        popMT10.add(mneDVT10);

        mneBMV11.setText("Bật Máy");
        popMV11.add(mneBMV11);

        mneDVT11.setText("Sử Dụng Dịch Vụ");
        popMV11.add(mneDVT11);

        mneBMV12.setText("Bật Máy");
        popMV12.add(mneBMV12);

        mneDVT12.setText("Sử Dụng Dịch Vụ");
        popMV12.add(mneDVT12);

        mneBMV13.setText("Bật Máy");
        popMV13.add(mneBMV13);

        mneDVT13.setText("Sử Dụng Dịch Vụ");
        popMV13.add(mneDVT13);

        mneBMV14.setText("Bật Máy");
        popMV14.add(mneBMV14);

        mneDVT14.setText("Sử Dụng Dịch Vụ");
        popMV14.add(mneDVT14);

        mneBMV15.setText("Bật Máy");
        popMV15.add(mneBMV15);

        mneDVT15.setText("Sử Dụng Dịch Vụ");
        popMV15.add(mneDVT15);

        mneBMV16.setText("Bật Máy");
        popMV16.add(mneBMV16);

        mneDVT16.setText("Sử Dụng Dịch Vụ");
        popMV16.add(mneDVT16);

        mneBMV17.setText("Bật Máy");
        popMV17.add(mneBMV17);

        mneDVT17.setText("Sử Dụng Dịch Vụ");
        popMV17.add(mneDVT17);

        mneBMV18.setText("Bật Máy");
        popMV18.add(mneBMV18);

        mneDVT18.setText("Sử Dụng Dịch Vụ");
        popMV18.add(mneDVT18);

        mneBMV19.setText("Bật Máy");
        popMV19.add(mneBMV19);

        mneDVT19.setText("Sử Dụng Dịch Vụ");
        popMV19.add(mneDVT19);

        mneBMV20.setText("Bật Máy");
        popMV20.add(mneBMV20);

        mneDVT20.setText("Sử Dụng Dịch Vụ");
        popMV20.add(mneDVT20);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        May1.setBackground(new java.awt.Color(0, 255, 51));
        May1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May1MouseClicked(evt);
            }
        });

        lblMay1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay1.setText("Máy 1");

        javax.swing.GroupLayout May1Layout = new javax.swing.GroupLayout(May1);
        May1.setLayout(May1Layout);
        May1Layout.setHorizontalGroup(
            May1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May1Layout.createSequentialGroup()
                .addGroup(May1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(May1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(May1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(May1Layout.createSequentialGroup()
                                .addComponent(lblKhachHang1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMay1))
                            .addComponent(lblGBD1)
                            .addGroup(May1Layout.createSequentialGroup()
                                .addComponent(lblTrangThai1)
                                .addGap(66, 66, 66))))
                    .addGroup(May1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNgay1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        May1Layout.setVerticalGroup(
            May1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(May1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May1Layout.createSequentialGroup()
                        .addComponent(lblKhachHang1)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May1Layout.createSequentialGroup()
                        .addComponent(lblMay1)
                        .addGap(28, 28, 28)))
                .addComponent(lblNgay1)
                .addGap(8, 8, 8)
                .addComponent(lblGBD1)
                .addGap(18, 18, 18)
                .addComponent(lblTrangThai1)
                .addGap(24, 24, 24))
        );

        May3.setBackground(new java.awt.Color(0, 255, 51));
        May3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May3MouseClicked(evt);
            }
        });

        lblMay3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay3.setText("Máy 3");

        javax.swing.GroupLayout May3Layout = new javax.swing.GroupLayout(May3);
        May3.setLayout(May3Layout);
        May3Layout.setHorizontalGroup(
            May3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblMay3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        May3Layout.setVerticalGroup(
            May3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May3Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(lblMay3)
                .addGap(76, 76, 76))
        );

        May5.setBackground(new java.awt.Color(0, 255, 51));
        May5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May5MouseClicked(evt);
            }
        });

        lblMay5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay5.setText("Máy 5");

        javax.swing.GroupLayout May5Layout = new javax.swing.GroupLayout(May5);
        May5.setLayout(May5Layout);
        May5Layout.setHorizontalGroup(
            May5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblMay5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        May5Layout.setVerticalGroup(
            May5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May5Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(lblMay5)
                .addGap(72, 72, 72))
        );

        May2.setBackground(new java.awt.Color(0, 255, 51));
        May2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May2MouseClicked(evt);
            }
        });

        lblMay2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay2.setText("Máy 2");

        javax.swing.GroupLayout May2Layout = new javax.swing.GroupLayout(May2);
        May2.setLayout(May2Layout);
        May2Layout.setHorizontalGroup(
            May2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblMay2)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        May2Layout.setVerticalGroup(
            May2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblMay2)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        May6.setBackground(new java.awt.Color(0, 255, 51));
        May6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May6MouseClicked(evt);
            }
        });

        lblMay6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay6.setText("Máy 6");

        javax.swing.GroupLayout May6Layout = new javax.swing.GroupLayout(May6);
        May6.setLayout(May6Layout);
        May6Layout.setHorizontalGroup(
            May6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblMay6)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        May6Layout.setVerticalGroup(
            May6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May6Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblMay6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        May4.setBackground(new java.awt.Color(0, 255, 51));
        May4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May4MouseClicked(evt);
            }
        });

        lblMay4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay4.setText("Máy 4");

        javax.swing.GroupLayout May4Layout = new javax.swing.GroupLayout(May4);
        May4.setLayout(May4Layout);
        May4Layout.setHorizontalGroup(
            May4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMay4)
                .addGap(52, 52, 52))
        );
        May4Layout.setVerticalGroup(
            May4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May4Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(lblMay4)
                .addGap(76, 76, 76))
        );

        May7.setBackground(new java.awt.Color(0, 255, 51));
        May7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May7MouseClicked(evt);
            }
        });

        lblMay7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay7.setText("Máy 7");

        javax.swing.GroupLayout May7Layout = new javax.swing.GroupLayout(May7);
        May7.setLayout(May7Layout);
        May7Layout.setHorizontalGroup(
            May7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMay7)
                .addGap(53, 53, 53))
        );
        May7Layout.setVerticalGroup(
            May7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblMay7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        May8.setBackground(new java.awt.Color(0, 255, 51));
        May8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May8MouseClicked(evt);
            }
        });

        lblMay8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay8.setText("Máy 8");

        javax.swing.GroupLayout May8Layout = new javax.swing.GroupLayout(May8);
        May8.setLayout(May8Layout);
        May8Layout.setHorizontalGroup(
            May8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May8Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblMay8)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        May8Layout.setVerticalGroup(
            May8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May8Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblMay8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        May9.setBackground(new java.awt.Color(0, 255, 51));
        May9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May9MouseClicked(evt);
            }
        });

        lblMay9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay9.setText("Máy 9");

        javax.swing.GroupLayout May9Layout = new javax.swing.GroupLayout(May9);
        May9.setLayout(May9Layout);
        May9Layout.setHorizontalGroup(
            May9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May9Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblMay9)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        May9Layout.setVerticalGroup(
            May9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May9Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblMay9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        May10.setBackground(new java.awt.Color(0, 255, 51));
        May10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May10MouseClicked(evt);
            }
        });

        lblMay10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay10.setText("Máy 10");

        javax.swing.GroupLayout May10Layout = new javax.swing.GroupLayout(May10);
        May10.setLayout(May10Layout);
        May10Layout.setHorizontalGroup(
            May10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May10Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblMay10)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        May10Layout.setVerticalGroup(
            May10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May10Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblMay10)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel45.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel46.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel47.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel48.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(May1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(May2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(May6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(May7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(May3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(May4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(May5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(May4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(May6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thường", jPanel2);

        May11.setBackground(new java.awt.Color(0, 255, 51));
        May11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May11MouseClicked(evt);
            }
        });

        lblMay11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay11.setText("Máy 11");

        javax.swing.GroupLayout May11Layout = new javax.swing.GroupLayout(May11);
        May11.setLayout(May11Layout);
        May11Layout.setHorizontalGroup(
            May11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May11Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblMay11)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        May11Layout.setVerticalGroup(
            May11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May11Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblMay11)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        May13.setBackground(new java.awt.Color(0, 255, 51));
        May13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May13MouseClicked(evt);
            }
        });

        lblMay13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay13.setText("Máy 13");

        javax.swing.GroupLayout May13Layout = new javax.swing.GroupLayout(May13);
        May13.setLayout(May13Layout);
        May13Layout.setHorizontalGroup(
            May13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMay13)
                .addGap(47, 47, 47))
        );
        May13Layout.setVerticalGroup(
            May13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May13Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblMay13)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        May15.setBackground(new java.awt.Color(0, 255, 51));
        May15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May15MouseClicked(evt);
            }
        });

        lblMay15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay15.setText("Máy 15");

        javax.swing.GroupLayout May15Layout = new javax.swing.GroupLayout(May15);
        May15.setLayout(May15Layout);
        May15Layout.setHorizontalGroup(
            May15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May15Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblMay15)
                .addGap(48, 48, 48))
        );
        May15Layout.setVerticalGroup(
            May15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May15Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblMay15)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        May12.setBackground(new java.awt.Color(0, 255, 51));
        May12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May12MouseClicked(evt);
            }
        });

        lblMay12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay12.setText("Máy 12");

        javax.swing.GroupLayout May12Layout = new javax.swing.GroupLayout(May12);
        May12.setLayout(May12Layout);
        May12Layout.setHorizontalGroup(
            May12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May12Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblMay12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
        May12Layout.setVerticalGroup(
            May12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May12Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblMay12)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        May16.setBackground(new java.awt.Color(0, 255, 51));
        May16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May16MouseClicked(evt);
            }
        });

        lblMay16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay16.setText("Máy 16");

        javax.swing.GroupLayout May16Layout = new javax.swing.GroupLayout(May16);
        May16.setLayout(May16Layout);
        May16Layout.setHorizontalGroup(
            May16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May16Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblMay16)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        May16Layout.setVerticalGroup(
            May16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May16Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblMay16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        May14.setBackground(new java.awt.Color(0, 255, 51));
        May14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May14MouseClicked(evt);
            }
        });

        lblMay14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay14.setText("Máy 14");

        javax.swing.GroupLayout May14Layout = new javax.swing.GroupLayout(May14);
        May14.setLayout(May14Layout);
        May14Layout.setHorizontalGroup(
            May14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMay14)
                .addGap(48, 48, 48))
        );
        May14Layout.setVerticalGroup(
            May14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May14Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblMay14)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        May17.setBackground(new java.awt.Color(0, 255, 51));
        May17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May17MouseClicked(evt);
            }
        });

        lblMay17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay17.setText("Máy 17");

        javax.swing.GroupLayout May17Layout = new javax.swing.GroupLayout(May17);
        May17.setLayout(May17Layout);
        May17Layout.setHorizontalGroup(
            May17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMay17)
                .addGap(48, 48, 48))
        );
        May17Layout.setVerticalGroup(
            May17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May17Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblMay17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        May18.setBackground(new java.awt.Color(0, 255, 51));
        May18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May18MouseClicked(evt);
            }
        });

        lblMay18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay18.setText("Máy 18");

        javax.swing.GroupLayout May18Layout = new javax.swing.GroupLayout(May18);
        May18.setLayout(May18Layout);
        May18Layout.setHorizontalGroup(
            May18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May18Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblMay18)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        May18Layout.setVerticalGroup(
            May18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May18Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblMay18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        May19.setBackground(new java.awt.Color(0, 255, 51));
        May19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May19MouseClicked(evt);
            }
        });

        lblMay19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay19.setText("Máy 19");

        javax.swing.GroupLayout May19Layout = new javax.swing.GroupLayout(May19);
        May19.setLayout(May19Layout);
        May19Layout.setHorizontalGroup(
            May19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May19Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(lblMay19)
                .addGap(49, 49, 49))
        );
        May19Layout.setVerticalGroup(
            May19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May19Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblMay19)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        May20.setBackground(new java.awt.Color(0, 255, 51));
        May20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                May20MouseClicked(evt);
            }
        });

        lblMay20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMay20.setText("Máy 20");

        javax.swing.GroupLayout May20Layout = new javax.swing.GroupLayout(May20);
        May20.setLayout(May20Layout);
        May20Layout.setHorizontalGroup(
            May20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, May20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMay20)
                .addGap(48, 48, 48))
        );
        May20Layout.setVerticalGroup(
            May20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(May20Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblMay20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel49.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel50.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel51.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel52.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jPanel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(May11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(May12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(May16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(May17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(May13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(May14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(May15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(May14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(May15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(May12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(May11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(May13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(May16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(May20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vip", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void May1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May1MouseClicked
        popMT1.show(May1, evt.getX(), evt.getY());
    }//GEN-LAST:event_May1MouseClicked

    private void May3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May3MouseClicked
        popMT3.show(May3, evt.getX(), evt.getY());
    }//GEN-LAST:event_May3MouseClicked

    private void May5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May5MouseClicked
        popMT5.show(May5, evt.getX(), evt.getY());
    }//GEN-LAST:event_May5MouseClicked

    private void May2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May2MouseClicked
        popMT2.show(May2, evt.getX(), evt.getY());
    }//GEN-LAST:event_May2MouseClicked

    private void May6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May6MouseClicked
        popMT6.show(May6, evt.getX(), evt.getY());
    }//GEN-LAST:event_May6MouseClicked

    private void May4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May4MouseClicked
        popMT4.show(May4, evt.getX(), evt.getY());
    }//GEN-LAST:event_May4MouseClicked

    private void May7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May7MouseClicked
        popMT7.show(May7, evt.getX(), evt.getY());
    }//GEN-LAST:event_May7MouseClicked

    private void May8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May8MouseClicked
        popMT8.show(May8, evt.getX(), evt.getY());
    }//GEN-LAST:event_May8MouseClicked

    private void May9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May9MouseClicked
        popMT9.show(May9, evt.getX(), evt.getY());
    }//GEN-LAST:event_May9MouseClicked

    private void May10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May10MouseClicked
        popMT10.show(May10, evt.getX(), evt.getY());
    }//GEN-LAST:event_May10MouseClicked

    private void May11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May11MouseClicked
        popMV11.show(May11, evt.getX(), evt.getY());
    }//GEN-LAST:event_May11MouseClicked

    private void May13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May13MouseClicked
        popMV13.show(May13, evt.getX(), evt.getY());
    }//GEN-LAST:event_May13MouseClicked

    private void May15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May15MouseClicked
        popMV15.show(May15, evt.getX(), evt.getY());
    }//GEN-LAST:event_May15MouseClicked

    private void May12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May12MouseClicked
        popMV12.show(May12, evt.getX(), evt.getY());
    }//GEN-LAST:event_May12MouseClicked

    private void May16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May16MouseClicked
        popMV16.show(May16, evt.getX(), evt.getY());
    }//GEN-LAST:event_May16MouseClicked

    private void May14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May14MouseClicked
        popMV14.show(May14, evt.getX(), evt.getY());
    }//GEN-LAST:event_May14MouseClicked

    private void May17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May17MouseClicked
        popMV17.show(May17, evt.getX(), evt.getY());
    }//GEN-LAST:event_May17MouseClicked

    private void May18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May18MouseClicked
        popMV18.show(May18, evt.getX(), evt.getY());
    }//GEN-LAST:event_May18MouseClicked

    private void May19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May19MouseClicked
        popMV19.show(May19, evt.getX(), evt.getY());
    }//GEN-LAST:event_May19MouseClicked

    private void May20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_May20MouseClicked
        popMV20.show(May20, evt.getX(), evt.getY());
    }//GEN-LAST:event_May20MouseClicked

    private void mneBMT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneBMT2ActionPerformed

    }//GEN-LAST:event_mneBMT2ActionPerformed

    private void mneBMT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneBMT3ActionPerformed

    }//GEN-LAST:event_mneBMT3ActionPerformed

    private void mneBMT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneBMT1ActionPerformed
        new KhachHangUI().setVisible(true);
    }//GEN-LAST:event_mneBMT1ActionPerformed

    private void mneDVT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneDVT1ActionPerformed
        new HoaDonUI().setVisible(true);
    }//GEN-LAST:event_mneDVT1ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.dispose();
        new TongUI().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_GioChoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel May1;
    private javax.swing.JPanel May10;
    private javax.swing.JPanel May11;
    private javax.swing.JPanel May12;
    private javax.swing.JPanel May13;
    private javax.swing.JPanel May14;
    private javax.swing.JPanel May15;
    private javax.swing.JPanel May16;
    private javax.swing.JPanel May17;
    private javax.swing.JPanel May18;
    private javax.swing.JPanel May19;
    private javax.swing.JPanel May2;
    private javax.swing.JPanel May20;
    private javax.swing.JPanel May3;
    private javax.swing.JPanel May4;
    private javax.swing.JPanel May5;
    private javax.swing.JPanel May6;
    private javax.swing.JPanel May7;
    private javax.swing.JPanel May8;
    private javax.swing.JPanel May9;
    private javax.swing.JButton btnHome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblGBD1;
    private javax.swing.JLabel lblKhachHang1;
    private javax.swing.JLabel lblMay1;
    private javax.swing.JLabel lblMay10;
    private javax.swing.JLabel lblMay11;
    private javax.swing.JLabel lblMay12;
    private javax.swing.JLabel lblMay13;
    private javax.swing.JLabel lblMay14;
    private javax.swing.JLabel lblMay15;
    private javax.swing.JLabel lblMay16;
    private javax.swing.JLabel lblMay17;
    private javax.swing.JLabel lblMay18;
    private javax.swing.JLabel lblMay19;
    private javax.swing.JLabel lblMay2;
    private javax.swing.JLabel lblMay20;
    private javax.swing.JLabel lblMay3;
    private javax.swing.JLabel lblMay4;
    private javax.swing.JLabel lblMay5;
    private javax.swing.JLabel lblMay6;
    private javax.swing.JLabel lblMay7;
    private javax.swing.JLabel lblMay8;
    private javax.swing.JLabel lblMay9;
    private javax.swing.JLabel lblNgay1;
    private javax.swing.JLabel lblTrangThai1;
    private javax.swing.JMenuItem mneBMT1;
    private javax.swing.JMenuItem mneBMT10;
    private javax.swing.JMenuItem mneBMT2;
    private javax.swing.JMenuItem mneBMT3;
    private javax.swing.JMenuItem mneBMT4;
    private javax.swing.JMenuItem mneBMT5;
    private javax.swing.JMenuItem mneBMT6;
    private javax.swing.JMenuItem mneBMT7;
    private javax.swing.JMenuItem mneBMT8;
    private javax.swing.JMenuItem mneBMT9;
    private javax.swing.JMenuItem mneBMV11;
    private javax.swing.JMenuItem mneBMV12;
    private javax.swing.JMenuItem mneBMV13;
    private javax.swing.JMenuItem mneBMV14;
    private javax.swing.JMenuItem mneBMV15;
    private javax.swing.JMenuItem mneBMV16;
    private javax.swing.JMenuItem mneBMV17;
    private javax.swing.JMenuItem mneBMV18;
    private javax.swing.JMenuItem mneBMV19;
    private javax.swing.JMenuItem mneBMV20;
    private javax.swing.JMenuItem mneDVT1;
    private javax.swing.JMenuItem mneDVT10;
    private javax.swing.JMenuItem mneDVT11;
    private javax.swing.JMenuItem mneDVT12;
    private javax.swing.JMenuItem mneDVT13;
    private javax.swing.JMenuItem mneDVT14;
    private javax.swing.JMenuItem mneDVT15;
    private javax.swing.JMenuItem mneDVT16;
    private javax.swing.JMenuItem mneDVT17;
    private javax.swing.JMenuItem mneDVT18;
    private javax.swing.JMenuItem mneDVT19;
    private javax.swing.JMenuItem mneDVT2;
    private javax.swing.JMenuItem mneDVT20;
    private javax.swing.JMenuItem mneDVT3;
    private javax.swing.JMenuItem mneDVT4;
    private javax.swing.JMenuItem mneDVT5;
    private javax.swing.JMenuItem mneDVT6;
    private javax.swing.JMenuItem mneDVT7;
    private javax.swing.JMenuItem mneDVT8;
    private javax.swing.JMenuItem mneDVT9;
    private javax.swing.JPopupMenu popMT1;
    private javax.swing.JPopupMenu popMT10;
    private javax.swing.JPopupMenu popMT2;
    private javax.swing.JPopupMenu popMT3;
    private javax.swing.JPopupMenu popMT4;
    private javax.swing.JPopupMenu popMT5;
    private javax.swing.JPopupMenu popMT6;
    private javax.swing.JPopupMenu popMT7;
    private javax.swing.JPopupMenu popMT8;
    private javax.swing.JPopupMenu popMT9;
    private javax.swing.JPopupMenu popMV11;
    private javax.swing.JPopupMenu popMV12;
    private javax.swing.JPopupMenu popMV13;
    private javax.swing.JPopupMenu popMV14;
    private javax.swing.JPopupMenu popMV15;
    private javax.swing.JPopupMenu popMV16;
    private javax.swing.JPopupMenu popMV17;
    private javax.swing.JPopupMenu popMV18;
    private javax.swing.JPopupMenu popMV19;
    private javax.swing.JPopupMenu popMV20;
    // End of variables declaration//GEN-END:variables
}
